# -*- coding: utf-8 -*-
"""ABC-COLAB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaU-Gu6gBVp1PTQuTQgqHd9HdMavLvbq
"""

import pandas as pd
df = pd.read_csv('inventory_dataset.csv')
df.head()

df['Sales_Value'] = df['Daily_Sales_Rate'] * df['Unit_Cost']
df = df.sort_values(by='Sales_Value', ascending=False).reset_index(drop=True)
df.head()

df['Cumulative_Sales'] = df['Sales_Value'].cumsum()
total_sales = df['Sales_Value'].sum()
df['Cumulative_Percentage'] = (df['Cumulative_Sales'] / total_sales) * 100
df.head()

def classify_abc(pct):
    if pct <= 80:
        return 'A'
    elif pct <= 95:
        return 'B'
    else:
        return 'C'

df['ABC_Category'] = df['Cumulative_Percentage'].apply(classify_abc)

df[['Product_Name', 'Sales_Value', 'Cumulative_Percentage', 'ABC_Category']]

from google.colab import files
files.download('ABC-SBDSS.csv')